apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.name" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.envVars }}
  {{ $key | upper }}: {{ $value | quote }}
{{-  end }}
