{{- if .Values.envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.name" . }}
  labels:
    app: {{ template "common.name" . }}
    chart: {{ template "common.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- range $key, $value := $.Values.secrets -}}
    {{ $key | upper | nindent 2 }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end -}}
